apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: consumer-group-1
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: QUIZ_TOPIC
      value: "leesah-quiz.leesah-rapid-v2"

